before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5 -5

sudo: enabled
language:
  - rust
  - cpp
compiler:
  - gcc
rust: nightly
script: ./test.sh
