[package]
name = "miniz_oxide_c_api"
version = "0.1.0"
build = "src/build.rs"
license = "MIT"
authors = ["Frommi <daniil.liferenko@gmail.com>"]

[workspace]

[lib]
name = "miniz_oxide_c_api"
crate-type = ['staticlib', 'rlib']

[dependencies]
libc = "0.2.22"
adler32 = "1.0.2"
crc = "^1.0.0"
miniz_oxide = { path = "miniz_oxide" }

[build-dependencies]
gcc = "0.3"

[features]
default = ["build_orig_miniz"]
build_orig_miniz = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
