[package]
name = "miniz_oxide"
version = "0.1.0"
build = "src/build.rs"
license = "MIT"
authors = ["Frommi <daniil.liferenko@gmail.com>"]

[workspace]

[lib]
name = "miniz_oxide"
crate-type = ['staticlib', 'rlib']

[dependencies]
libc = "0.2.22"
adler32 = "1.0.2"
crc = "^1.0.0"

[build-dependencies]
gcc = "0.3"

[features]
default = ["build_non_rust"]
fuzzing = []
bench = ["build_non_rust"]
build_non_rust = []

[profile.dev]
panic = "abort"

