[package]
name = "miniz_oxide"
version = "0.1.0"
authors = ["Frommi <daniil.liferenko@gmail.com>"]

[lib]
name = "miniz_oxide"
crate-type = ["staticlib"]

[dependencies]
libc="0.2.22"

[profile.dev]
panic = "abort"
